# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

jobs:

- job: 'Test'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install robotframework robotframework-seleniumlibrary==6.0.0 && npm install chromedriver --detect_chromedriver_version
    displayName: 'Install dependencies'

  - powershell: pip list
    displayName: 'list version1'

  - script: pip install selenium==4.9.0
    displayName: 'install older'

  - powershell: pip list
    displayName: 'list version2'

  - powershell: robot --pythonpath . -d .\ -x outputxunit.xml testi.robot
    displayName: 'Run Robot Scripts'