# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

jobs:

- job: 'Test'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install robotframework robotframework-seleniumlibrary && npm install chromedriver
    displayName: 'Install dependencies'
  
  - powershell: robot --pythonpath . -d .\ -x outputxunit.xml testi.robot
    displayName: 'Run Robot Scripts'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      searchFolder: 'D:\a\1\s\'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results outputxunit.xml'